export const dataRiders = [{ "id": 1, "name": "Simona", "value": 82, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 26, "team": "NeoStrata Company Inc", "country": "Czech Republic" },
{ "id": 2, "name": "Maurie", "value": 91, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 26, "team": "Lupin Pharmaceuticals, Inc", "country": "Panama" },
{ "id": 3, "name": "Donia", "value": 98, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 48, "team": "Upstate Pharma, LLC", "country": "France" },
{ "id": 4, "name": "Latisha", "value": 150, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 38, "team": "Wockhardt Limited", "country": "Japan" },
{ "id": 5, "name": "Nicki", "value": 46, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 32, "team": "Novartis Consumer Health, Inc.", "country": "Armenia" },
{ "id": 6, "name": "Hazel", "value": 194, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 43, "team": "NATURE REPUBLIC CO., LTD.", "country": "Cambodia" },
{ "id": 7, "name": "Gabrielle", "value": 4, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 39, "team": "Acme United Corporation", "country": "Sweden" },
{ "id": 8, "name": "Doug", "value": 152, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 44, "team": "WIZCOZ CORPORATION LTD", "country": "Philippines" },
{ "id": 9, "name": "Kitty", "value": 14, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 26, "team": "Amneal Pharmaceuticals, LLC", "country": "Philippines" },
{ "id": 10, "name": "Conni", "value": 119, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 47, "team": "Deseret Biologicals, Inc", "country": "China" },
{ "id": 11, "name": "Nelson", "value": 133, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 19, "team": "WOONSOCKET PRESCRIPTION CENTER,INCORPORATED", "country": "Sweden" },
{ "id": 12, "name": "Annie", "value": 145, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 24, "team": "Sandoz Inc", "country": "China" },
{ "id": 13, "name": "Salem", "value": 38, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 36, "team": "Kosan Kozmetik Sanayi ve Ticaret A.S.", "country": "Senegal" },
{ "id": 14, "name": "Yule", "value": 88, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 22, "team": "Ventura Corporation (San Juan, P.R)", "country": "France" },
{ "id": 15, "name": "Charlena", "value": 24, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 31, "team": "Janssen Pharmaceuticals, Inc.", "country": "China" },
{ "id": 16, "name": "Dulcie", "value": 130, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 21, "team": "Ionx Holdings d/b/a HelloLife", "country": "Indonesia" },
{ "id": 17, "name": "Celestia", "value": 132, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 48, "team": "Sungwon Pharmaceutical Co., Ltd.", "country": "Japan" },
{ "id": 18, "name": "Alli", "value": 109, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 45, "team": "Unifirst First Aid Corporation", "country": "United Kingdom" },
{ "id": 19, "name": "Kelci", "value": 15, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 22, "team": "Dolgencorp Inc", "country": "China" },
{ "id": 20, "name": "Bradan", "value": 111, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 47, "team": "AMERICAN SALES COMPANY", "country": "Vanuatu" },
{ "id": 21, "name": "Sephira", "value": 181, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 42, "team": "Sandoz Inc", "country": "Guatemala" },
{ "id": 22, "name": "Avis", "value": 40, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 25, "team": "REMEDYREPACK INC.", "country": "China" },
{ "id": 23, "name": "Caitrin", "value": 144, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 20, "team": "Heritage Pharmaceuticals Inc.", "country": "Sweden" },
{ "id": 24, "name": "Tessa", "value": 30, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 26, "team": "Antigen Laboratories, Inc.", "country": "Azerbaijan" },
{ "id": 25, "name": "Kent", "value": 33, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 33, "team": "Cardinal Health", "country": "Brazil" },
{ "id": 26, "name": "Sanford", "value": 99, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 36, "team": "Apotex Corp.", "country": "Jamaica" },
{ "id": 27, "name": "Shari", "value": 185, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 41, "team": "Tom's of Maine, Inc.", "country": "China" },
{ "id": 28, "name": "Alexi", "value": 43, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 25, "team": "Mycone Dental Supply Co., Inc DBA Keystone Industries and Deepak Products Inc.", "country": "China" },
{ "id": 29, "name": "Sterling", "value": 70, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 49, "team": "Ecolab Inc.", "country": "China" },
{ "id": 30, "name": "Nisse", "value": 27, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 36, "team": "Qualitest Pharmaceuticals", "country": "Portugal" },
{ "id": 31, "name": "Allie", "value": 126, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 26, "team": "Major Pharmaceuticals", "country": "United States" },
{ "id": 32, "name": "Meriel", "value": 63, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 40, "team": "Miers Laboratories", "country": "Portugal" },
{ "id": 33, "name": "Gilbertina", "value": 44, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 47, "team": "Bryant Ranch Prepack", "country": "Colombia" },
{ "id": 34, "name": "Sylas", "value": 142, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 32, "team": "Geiss, Destin + Dunn, Inc", "country": "Armenia" },
{ "id": 35, "name": "Vivien", "value": 75, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 43, "team": "Hospira, Inc.", "country": "Vietnam" },
{ "id": 36, "name": "Dwain", "value": 11, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 23, "team": "Rebel Distributors Corp", "country": "Greece" },
{ "id": 37, "name": "Jasun", "value": 55, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 36, "team": "Lake Erie Medical DBA Quality Care Products LLC", "country": "Indonesia" },
{ "id": 38, "name": "Cherrita", "value": 176, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 18, "team": "H E B", "country": "China" },
{ "id": 39, "name": "Edie", "value": 93, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 49, "team": "Mylan Pharmaceuticals Inc.", "country": "Maldives" },
{ "id": 40, "name": "Cynthie", "value": 99, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 50, "team": "REMEDYREPACK INC.", "country": "Dominican Republic" },
{ "id": 41, "name": "Essie", "value": 74, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 43, "team": "UNITED EXCHANGE CORP.", "country": "China" },
{ "id": 42, "name": "Bibbye", "value": 135, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 18, "team": "ALK-Abello, Inc.", "country": "Mongolia" },
{ "id": 43, "name": "Carmelle", "value": 186, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 26, "team": "Altura Pharmaceuticals, Inc.", "country": "Belarus" },
{ "id": 44, "name": "Trent", "value": 62, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 20, "team": "Hospira, Inc.", "country": "China" },
{ "id": 45, "name": "Hersch", "value": 96, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 46, "team": "PharmaCare US, Inc.", "country": "Indonesia" },
{ "id": 46, "name": "Lyle", "value": 6, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 47, "team": "CVS Pharmacy", "country": "Gambia" },
{ "id": 47, "name": "Lexy", "value": 198, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 23, "team": "Rebel Distributors Corp", "country": "Slovenia" },
{ "id": 48, "name": "Danie", "value": 186, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 40, "team": "West-Ward Pharmaceutical Corp.", "country": "Peru" },
{ "id": 49, "name": "Enriqueta", "value": 39, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 25, "team": "UDL Laboratories, Inc.", "country": "France" },
{ "id": 50, "name": "Flore", "value": 44, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 43, "team": "KANEBO COSMETICS INC.", "country": "Russia" },
{ "id": 51, "name": "Joey", "value": 171, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 48, "team": "American Sales Company", "country": "United States" },
{ "id": 52, "name": "Alvy", "value": 21, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 41, "team": "WOCKHARDT LIMITED", "country": "Indonesia" },
{ "id": 53, "name": "Eleonore", "value": 152, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 37, "team": "Jouer Cosmetics LLC", "country": "China" },
{ "id": 54, "name": "Deny", "value": 198, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 39, "team": "Bryant Ranch Prepack", "country": "Indonesia" },
{ "id": 55, "name": "Link", "value": 37, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 44, "team": "Church & Dwight Co., Inc.", "country": "Colombia" },
{ "id": 56, "name": "Shaylynn", "value": 100, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 33, "team": "Bryant Ranch Prepack", "country": "Mexico" },
{ "id": 57, "name": "Webster", "value": 136, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 27, "team": "Cardinal Health", "country": "Colombia" },
{ "id": 58, "name": "Sadie", "value": 158, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 30, "team": "Parfums Christian Dior", "country": "China" },
{ "id": 59, "name": "Ivie", "value": 52, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 20, "team": "Novartis Vaccines and Diagnostics GmbH", "country": "South Korea" },
{ "id": 60, "name": "Ambros", "value": 25, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 26, "team": "Global Pharmaceuticals, Division of Impax Laboratories Inc.", "country": "China" },
{ "id": 61, "name": "Caterina", "value": 83, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 20, "team": "Aurobindo Pharma Limited", "country": "Indonesia" },
{ "id": 62, "name": "Waverly", "value": 163, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 19, "team": "Cangene bioPharma Inc.", "country": "Portugal" },
{ "id": 63, "name": "Rustin", "value": 161, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 49, "team": "Reckitt Benckiser LLC", "country": "Indonesia" },
{ "id": 64, "name": "Blanca", "value": 17, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 38, "team": "Hyland's", "country": "Macedonia" },
{ "id": 65, "name": "Otha", "value": 11, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 21, "team": "Aphena Pharma Solutions - Tennessee, LLC", "country": "Guatemala" },
{ "id": 66, "name": "Fairfax", "value": 153, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 34, "team": "MineralBio", "country": "Afghanistan" },
{ "id": 67, "name": "Chicky", "value": 160, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 21, "team": "Ventura Corporation LTD", "country": "Poland" },
{ "id": 68, "name": "Greta", "value": 146, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 46, "team": "BCM Ltd", "country": "Russia" },
{ "id": 69, "name": "Augustine", "value": 181, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 40, "team": "HEB", "country": "Laos" },
{ "id": 70, "name": "Elinor", "value": 123, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 41, "team": "SJ Creations, Inc.", "country": "Chad" },
{ "id": 71, "name": "Lesley", "value": 163, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 29, "team": "Kroger Company", "country": "Honduras" },
{ "id": 72, "name": "Micky", "value": 20, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 43, "team": "Dr. Reddy's Laboratories Limited", "country": "Japan" },
{ "id": 73, "name": "Lucinda", "value": 119, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 36, "team": "King Bio Inc.", "country": "Poland" },
{ "id": 74, "name": "Xylina", "value": 35, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 33, "team": "Sandoz Inc", "country": "South Africa" },
{ "id": 75, "name": "Agatha", "value": 164, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 22, "team": "STAT RX USA LLC", "country": "Indonesia" },
{ "id": 76, "name": "Christoper", "value": 131, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 49, "team": "Ventura International LTD.", "country": "Russia" },
{ "id": 77, "name": "Nada", "value": 114, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 50, "team": "Native Remedies, LLC", "country": "Senegal" },
{ "id": 78, "name": "Moe", "value": 43, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 39, "team": "AGILA SPECIALTIES PRIVATE LIMITED", "country": "Indonesia" },
{ "id": 79, "name": "Marthena", "value": 131, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 50, "team": "Antigen Laboratories, Inc.", "country": "Philippines" },
{ "id": 80, "name": "Aura", "value": 68, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 25, "team": "ARMY AND AIR FORCE EXCHANGE SERVICE", "country": "Laos" },
{ "id": 81, "name": "Jilli", "value": 190, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 50, "team": "Allermed Laboratories, Inc.", "country": "Indonesia" },
{ "id": 82, "name": "Sidonnie", "value": 100, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 49, "team": "Antigen Laboratories, Inc.", "country": "China" },
{ "id": 83, "name": "Reagan", "value": 25, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 43, "team": "JAFRA COSMETICS INTERNATIONAL", "country": "Bulgaria" },
{ "id": 84, "name": "Manda", "value": 32, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 47, "team": "THEFACESHOP CO., LTD", "country": "France" },
{ "id": 85, "name": "Conrad", "value": 149, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 43, "team": "Zydus Pharmaceuticals (USA) Inc.", "country": "Malaysia" },
{ "id": 86, "name": "Grethel", "value": 120, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 21, "team": "Uriel Pharmacy Inc.", "country": "Portugal" },
{ "id": 87, "name": "Carrie", "value": 183, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 44, "team": "Fenwal Inc", "country": "Panama" },
{ "id": 88, "name": "Saleem", "value": 84, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 34, "team": "Carilion Materials Management", "country": "Portugal" },
{ "id": 89, "name": "Flemming", "value": 45, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 45, "team": "Physicians Total Care, Inc.", "country": "Finland" },
{ "id": 90, "name": "Brand", "value": 186, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 23, "team": "Heel Inc", "country": "United States" },
{ "id": 91, "name": "Alli", "value": 46, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 28, "team": "Bonne Bell LLC", "country": "Russia" },
{ "id": 92, "name": "Rickard", "value": 4, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 33, "team": "Hospira, Inc.", "country": "Peru" },
{ "id": 93, "name": "Virgilio", "value": 43, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 19, "team": "American Health Packaging", "country": "France" },
{ "id": 94, "name": "Hymie", "value": 65, "photo": "http://dummyimage.com/200x200.png/dddddd/000000", "age": 22, "team": "Northwind Pharmaceuticals", "country": "Portugal" },
{ "id": 95, "name": "Mariejeanne", "value": 75, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 44, "team": "Actavis Mid Atlantic LLC", "country": "United States" },
{ "id": 96, "name": "Edwin", "value": 161, "photo": "http://dummyimage.com/200x200.png/cc0000/ffffff", "age": 22, "team": "Golden State Medical Supply, Inc.", "country": "Comoros" },
{ "id": 97, "name": "Merry", "value": 29, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 26, "team": "Procter & Gamble Manufacturing Company", "country": "China" },
{ "id": 98, "name": "Barclay", "value": 104, "photo": "http://dummyimage.com/200x200.png/5fa2dd/ffffff", "age": 49, "team": "Cardinal Health", "country": "Sweden" },
{ "id": 99, "name": "Minne", "value": 28, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 33, "team": "CONOPCO Inc. d/b/a Unilever", "country": "China" },
{ "id": 100, "name": "Gun", "value": 5, "photo": "http://dummyimage.com/200x200.png/ff4444/ffffff", "age": 33, "team": "ALK-Abello, Inc.", "country": "Guatemala" }]

